name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          docker build -t spark-builder:latest -f Dockerfile.build .
          docker run -tv "$(pwd)/cache:/mnt" spark-builder:latest

          ./make-image.sh
